### ISSUE TITLE
Optimize container for docker compose

### ISSUE THREAD

**Issue by daniel-lerch** [siomiz/SoftEtherVPN#59]
Running this SoftEtherVPN container with docker compose is possible but not as easy as it could be.
Two relatively simple changes would help inexperienced users a lot:
1. Provide a default `docker-compose.yml` for download.
2. Make it possible to mount `vpn_server.config` in a separate folder. Although it's possible to mount it as a file, docker will create a new folder on startup. Mounting the file in a different folder would allow to start a container without changing the compose file or docker command after the first start.

If desired I could make a pull request for a default compose file which works for me.

**Comment by siomiz** [comment]
Added a very basic [`docker-compose.yml`](https://github.com/siomiz/SoftEtherVPN/blob/2d199b19f6cc9caa0b224982bd9e7bad02845101/docker-compose.yml) and empty [`vpn_server.config`](https://github.com/siomiz/SoftEtherVPN/blob/2d199b19f6cc9caa0b224982bd9e7bad02845101/vpn_server.config) for it to write config to (2d199b1).
It's difficult to change the config file location arbitrary because the server exec does not have argument to specify it (there is a server command [`ConfigSet`](https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.3_VPN_Server_%2F%2F_VPN_Bridge_Management_Command_Reference_(For_Entire_Server)#6.3.43_.22ConfigSet.22:_Write_Configuration_File_to_VPN_Server)).

Pull requests are always welcome.
